// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game_write.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLineupEntry = `-- name: CreateLineupEntry :exec
INSERT INTO lineups (id, match_id, team_id, kind, variant_number, variant_name, player_id, batting_order, position, created_at, updated_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateLineupEntryParams struct {
	ID            string
	MatchID       string
	TeamID        string
	Kind          int16
	VariantNumber int16
	VariantName   string
	PlayerID      string
	BattingOrder  int16
	Position      int16
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

func (q *Queries) CreateLineupEntry(ctx context.Context, arg CreateLineupEntryParams) error {
	_, err := q.db.Exec(ctx, createLineupEntry,
		arg.ID,
		arg.MatchID,
		arg.TeamID,
		arg.Kind,
		arg.VariantNumber,
		arg.VariantName,
		arg.PlayerID,
		arg.BattingOrder,
		arg.Position,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const createMatch = `-- name: CreateMatch :exec
INSERT INTO matches (id, home_team_id, away_team_id, scheduled_at, location, status, created_at, updated_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateMatchParams struct {
	ID          string
	HomeTeamID  string
	AwayTeamID  string
	ScheduledAt pgtype.Timestamptz
	Location    string
	Status      int16
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) error {
	_, err := q.db.Exec(ctx, createMatch,
		arg.ID,
		arg.HomeTeamID,
		arg.AwayTeamID,
		arg.ScheduledAt,
		arg.Location,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const getLineupEntries = `-- name: GetLineupEntries :many
SELECT id::text, player_id::text, batting_order, position, variant_name, created_at, updated_at, deleted_at
FROM lineups
WHERE match_id = $1 AND team_id = $2 AND kind = $3 AND variant_number = $4 AND deleted_at IS NULL
ORDER BY batting_order, id
`

type GetLineupEntriesParams struct {
	MatchID       string
	TeamID        string
	Kind          int16
	VariantNumber int16
}

type GetLineupEntriesRow struct {
	ID           string
	PlayerID     string
	BattingOrder int16
	Position     int16
	VariantName  string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

func (q *Queries) GetLineupEntries(ctx context.Context, arg GetLineupEntriesParams) ([]GetLineupEntriesRow, error) {
	rows, err := q.db.Query(ctx, getLineupEntries,
		arg.MatchID,
		arg.TeamID,
		arg.Kind,
		arg.VariantNumber,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLineupEntriesRow{}
	for rows.Next() {
		var i GetLineupEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.BattingOrder,
			&i.Position,
			&i.VariantName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatch = `-- name: GetMatch :one
SELECT id::text, home_team_id::text, away_team_id::text, scheduled_at, location, status, created_at, updated_at, deleted_at
FROM matches
WHERE id = $1 AND deleted_at IS NULL
`

type GetMatchRow struct {
	ID          string
	HomeTeamID  string
	AwayTeamID  string
	ScheduledAt pgtype.Timestamptz
	Location    string
	Status      int16
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

func (q *Queries) GetMatch(ctx context.Context, id string) (GetMatchRow, error) {
	row := q.db.QueryRow(ctx, getMatch, id)
	var i GetMatchRow
	err := row.Scan(
		&i.ID,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.ScheduledAt,
		&i.Location,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const lineupNameOccupied = `-- name: LineupNameOccupied :one
SELECT EXISTS(
  SELECT 1 FROM lineups
  WHERE match_id = $1 AND team_id = $2 AND variant_name = $3 AND deleted_at IS NULL
    AND NOT (kind = $4 AND variant_number = $5)
)
`

type LineupNameOccupiedParams struct {
	MatchID       string
	TeamID        string
	VariantName   string
	Kind          int16
	VariantNumber int16
}

func (q *Queries) LineupNameOccupied(ctx context.Context, arg LineupNameOccupiedParams) (bool, error) {
	row := q.db.QueryRow(ctx, lineupNameOccupied,
		arg.MatchID,
		arg.TeamID,
		arg.VariantName,
		arg.Kind,
		arg.VariantNumber,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listLineupKeysByMatch = `-- name: ListLineupKeysByMatch :many
SELECT DISTINCT team_id::text, kind, variant_number
FROM lineups
WHERE match_id = $1 AND deleted_at IS NULL
ORDER BY 1, 2, 3
`

type ListLineupKeysByMatchRow struct {
	TeamID        string
	Kind          int16
	VariantNumber int16
}

func (q *Queries) ListLineupKeysByMatch(ctx context.Context, matchID string) ([]ListLineupKeysByMatchRow, error) {
	rows, err := q.db.Query(ctx, listLineupKeysByMatch, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLineupKeysByMatchRow{}
	for rows.Next() {
		var i ListLineupKeysByMatchRow
		if err := rows.Scan(&i.TeamID, &i.Kind, &i.VariantNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoredMatches = `-- name: ListStoredMatches :many
SELECT id::text, home_team_id::text, away_team_id::text, scheduled_at, location, status, created_at, updated_at, deleted_at
FROM matches
WHERE deleted_at IS NULL
ORDER BY scheduled_at, id
`

type ListStoredMatchesRow struct {
	ID          string
	HomeTeamID  string
	AwayTeamID  string
	ScheduledAt pgtype.Timestamptz
	Location    string
	Status      int16
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

func (q *Queries) ListStoredMatches(ctx context.Context) ([]ListStoredMatchesRow, error) {
	rows, err := q.db.Query(ctx, listStoredMatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStoredMatchesRow{}
	for rows.Next() {
		var i ListStoredMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.ScheduledAt,
			&i.Location,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteLineup = `-- name: SoftDeleteLineup :execrows
UPDATE lineups SET deleted_at = $1, updated_at = $1
WHERE match_id = $2 AND team_id = $3 AND kind = $4 AND variant_number = $5 AND deleted_at IS NULL
`

type SoftDeleteLineupParams struct {
	DeletedAt     pgtype.Timestamptz
	MatchID       string
	TeamID        string
	Kind          int16
	VariantNumber int16
}

func (q *Queries) SoftDeleteLineup(ctx context.Context, arg SoftDeleteLineupParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteLineup,
		arg.DeletedAt,
		arg.MatchID,
		arg.TeamID,
		arg.Kind,
		arg.VariantNumber,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteLineupsByMatch = `-- name: SoftDeleteLineupsByMatch :exec
UPDATE lineups SET deleted_at = $1, updated_at = $1
WHERE match_id = $2 AND deleted_at IS NULL
`

type SoftDeleteLineupsByMatchParams struct {
	DeletedAt pgtype.Timestamptz
	MatchID   string
}

func (q *Queries) SoftDeleteLineupsByMatch(ctx context.Context, arg SoftDeleteLineupsByMatchParams) error {
	_, err := q.db.Exec(ctx, softDeleteLineupsByMatch, arg.DeletedAt, arg.MatchID)
	return err
}

const updateMatch = `-- name: UpdateMatch :execrows
UPDATE matches
SET home_team_id = $1, away_team_id = $2, scheduled_at = $3, location = $4, status = $5,
    updated_at = $6, deleted_at = $7
WHERE id = $8 AND deleted_at IS NULL
`

type UpdateMatchParams struct {
	HomeTeamID  string
	AwayTeamID  string
	ScheduledAt pgtype.Timestamptz
	Location    string
	Status      int16
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	ID          string
}

func (q *Queries) UpdateMatch(ctx context.Context, arg UpdateMatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMatch,
		arg.HomeTeamID,
		arg.AwayTeamID,
		arg.ScheduledAt,
		arg.Location,
		arg.Status,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
