// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game_read.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listMatchFinalScores = `-- name: ListMatchFinalScores :many
SELECT DISTINCT ON (match_id) match_id::text, after_home_score, after_away_score
FROM plays
WHERE match_id = ANY($1::uuid[]) AND deleted_at IS NULL
ORDER BY match_id, sequence DESC
`

type ListMatchFinalScoresRow struct {
	MatchID        string
	AfterHomeScore int32
	AfterAwayScore int32
}

func (q *Queries) ListMatchFinalScores(ctx context.Context, matchIds []string) ([]ListMatchFinalScoresRow, error) {
	rows, err := q.db.Query(ctx, listMatchFinalScores, matchIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMatchFinalScoresRow{}
	for rows.Next() {
		var i ListMatchFinalScoresRow
		if err := rows.Scan(&i.MatchID, &i.AfterHomeScore, &i.AfterAwayScore); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchLineupRows = `-- name: ListMatchLineupRows :many
SELECT l.match_id::text,t.name AS team_name,l.kind,l.variant_number,l.variant_name,p.name AS player_name,p.jersey_number,l.batting_order,l.position,l.id::text AS entry_id
FROM lineups l JOIN teams t ON t.id=l.team_id AND t.deleted_at IS NULL JOIN players p ON p.id=l.player_id AND p.deleted_at IS NULL
WHERE l.match_id=ANY($1::uuid[]) AND l.deleted_at IS NULL
ORDER BY l.match_id,t.name,l.kind,l.variant_number,l.batting_order,l.id
`

type ListMatchLineupRowsRow struct {
	LMatchID      string
	TeamName      string
	Kind          int16
	VariantNumber int16
	VariantName   string
	PlayerName    string
	JerseyNumber  int16
	BattingOrder  int16
	Position      int16
	EntryID       string
}

func (q *Queries) ListMatchLineupRows(ctx context.Context, matchIds []string) ([]ListMatchLineupRowsRow, error) {
	rows, err := q.db.Query(ctx, listMatchLineupRows, matchIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMatchLineupRowsRow{}
	for rows.Next() {
		var i ListMatchLineupRowsRow
		if err := rows.Scan(
			&i.LMatchID,
			&i.TeamName,
			&i.Kind,
			&i.VariantNumber,
			&i.VariantName,
			&i.PlayerName,
			&i.JerseyNumber,
			&i.BattingOrder,
			&i.Position,
			&i.EntryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchRecordEvents = `-- name: ListMatchRecordEvents :many
SELECT p.match_id::text,p.id::text AS play_id,p.sequence,p.inning,p.half,p.batting_order,
 b.name AS batter_name,bt.name AS batter_team_name,b.jersey_number AS batter_jersey_number,
 sp.name AS pitcher_name,spt.name AS pitcher_team_name,sp.jersey_number AS pitcher_jersey_number,
 p.after_outs,p.after_home_score,p.after_away_score,p.batting_result,p.result_description
FROM plays p JOIN players b ON b.id=p.batter_id AND b.deleted_at IS NULL JOIN teams bt ON bt.id=b.team_id AND bt.deleted_at IS NULL
 JOIN players sp ON sp.id=p.starting_pitcher_id AND sp.deleted_at IS NULL JOIN teams spt ON spt.id=sp.team_id AND spt.deleted_at IS NULL
WHERE p.match_id=ANY($1::uuid[]) AND p.deleted_at IS NULL
ORDER BY p.match_id,p.sequence
`

type ListMatchRecordEventsRow struct {
	PMatchID            string
	PlayID              string
	Sequence            int32
	Inning              int16
	Half                int16
	BattingOrder        int16
	BatterName          string
	BatterTeamName      string
	BatterJerseyNumber  int16
	PitcherName         string
	PitcherTeamName     string
	PitcherJerseyNumber int16
	AfterOuts           int16
	AfterHomeScore      int32
	AfterAwayScore      int32
	BattingResult       int16
	ResultDescription   string
}

func (q *Queries) ListMatchRecordEvents(ctx context.Context, matchIds []string) ([]ListMatchRecordEventsRow, error) {
	rows, err := q.db.Query(ctx, listMatchRecordEvents, matchIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMatchRecordEventsRow{}
	for rows.Next() {
		var i ListMatchRecordEventsRow
		if err := rows.Scan(
			&i.PMatchID,
			&i.PlayID,
			&i.Sequence,
			&i.Inning,
			&i.Half,
			&i.BattingOrder,
			&i.BatterName,
			&i.BatterTeamName,
			&i.BatterJerseyNumber,
			&i.PitcherName,
			&i.PitcherTeamName,
			&i.PitcherJerseyNumber,
			&i.AfterOuts,
			&i.AfterHomeScore,
			&i.AfterAwayScore,
			&i.BattingResult,
			&i.ResultDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordFielding = `-- name: ListRecordFielding :many
SELECT f.play_id::text,f.sequence,p.name AS fielder_name,t.name AS fielder_team_name,p.jersey_number AS fielder_jersey_number,f.position,f.result,f.description
FROM play_fielding_results f JOIN players p ON p.id=f.fielder_id AND p.deleted_at IS NULL JOIN teams t ON t.id=p.team_id AND t.deleted_at IS NULL
WHERE f.play_id=ANY($1::uuid[]) AND f.deleted_at IS NULL ORDER BY f.play_id,f.sequence
`

type ListRecordFieldingRow struct {
	FPlayID             string
	Sequence            int16
	FielderName         string
	FielderTeamName     string
	FielderJerseyNumber int16
	Position            int16
	Result              int16
	Description         string
}

func (q *Queries) ListRecordFielding(ctx context.Context, playIds []string) ([]ListRecordFieldingRow, error) {
	rows, err := q.db.Query(ctx, listRecordFielding, playIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecordFieldingRow{}
	for rows.Next() {
		var i ListRecordFieldingRow
		if err := rows.Scan(
			&i.FPlayID,
			&i.Sequence,
			&i.FielderName,
			&i.FielderTeamName,
			&i.FielderJerseyNumber,
			&i.Position,
			&i.Result,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordPitches = `-- name: ListRecordPitches :many
SELECT p.play_id::text,p.sequence,pi.name AS pitcher_name,pit.name AS pitcher_team_name,pi.jersey_number AS pitcher_jersey_number,
 b.name AS batter_name,bt.name AS batter_team_name,b.jersey_number AS batter_jersey_number,p.result,p.balls_after,p.strikes_after,p.pitch_type,p.velocity,p.zone,p.description
FROM play_pitching_results p JOIN players pi ON pi.id=p.pitcher_id AND pi.deleted_at IS NULL JOIN teams pit ON pit.id=pi.team_id AND pit.deleted_at IS NULL
 JOIN players b ON b.id=p.batter_id AND b.deleted_at IS NULL JOIN teams bt ON bt.id=b.team_id AND bt.deleted_at IS NULL
WHERE p.play_id=ANY($1::uuid[]) AND p.deleted_at IS NULL ORDER BY p.play_id,p.sequence
`

type ListRecordPitchesRow struct {
	PPlayID             string
	Sequence            int16
	PitcherName         string
	PitcherTeamName     string
	PitcherJerseyNumber int16
	BatterName          string
	BatterTeamName      string
	BatterJerseyNumber  int16
	Result              int16
	BallsAfter          int16
	StrikesAfter        int16
	PitchType           string
	Velocity            *float64
	Zone                *int16
	Description         string
}

func (q *Queries) ListRecordPitches(ctx context.Context, playIds []string) ([]ListRecordPitchesRow, error) {
	rows, err := q.db.Query(ctx, listRecordPitches, playIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecordPitchesRow{}
	for rows.Next() {
		var i ListRecordPitchesRow
		if err := rows.Scan(
			&i.PPlayID,
			&i.Sequence,
			&i.PitcherName,
			&i.PitcherTeamName,
			&i.PitcherJerseyNumber,
			&i.BatterName,
			&i.BatterTeamName,
			&i.BatterJerseyNumber,
			&i.Result,
			&i.BallsAfter,
			&i.StrikesAfter,
			&i.PitchType,
			&i.Velocity,
			&i.Zone,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordRunners = `-- name: ListRecordRunners :many
SELECT r.play_id::text,r.sequence,pl.name AS runner_name,pt.name AS runner_team_name,pl.jersey_number AS runner_jersey_number,r.result,r.from_base,r.to_base,r.out_recorded,r.scored,
 cp.name AS charged_pitcher_name,cpt.name AS charged_pitcher_team_name,cp.jersey_number AS charged_pitcher_jersey_number,r.earned,
 rb.name AS rbi_batter_name,rbt.name AS rbi_batter_team_name,rb.jersey_number AS rbi_batter_jersey_number,r.description
FROM play_runner_results r JOIN players pl ON pl.id=r.runner_id AND pl.deleted_at IS NULL JOIN teams pt ON pt.id=pl.team_id AND pt.deleted_at IS NULL
 LEFT JOIN players cp ON cp.id=r.charged_pitcher_id AND cp.deleted_at IS NULL LEFT JOIN teams cpt ON cpt.id=cp.team_id AND cpt.deleted_at IS NULL
 LEFT JOIN players rb ON rb.id=r.rbi_batter_id AND rb.deleted_at IS NULL LEFT JOIN teams rbt ON rbt.id=rb.team_id AND rbt.deleted_at IS NULL
WHERE r.play_id=ANY($1::uuid[]) AND r.deleted_at IS NULL ORDER BY r.play_id,r.sequence
`

type ListRecordRunnersRow struct {
	RPlayID                    string
	Sequence                   int16
	RunnerName                 string
	RunnerTeamName             string
	RunnerJerseyNumber         int16
	Result                     int16
	FromBase                   int16
	ToBase                     *int16
	OutRecorded                bool
	Scored                     bool
	ChargedPitcherName         *string
	ChargedPitcherTeamName     *string
	ChargedPitcherJerseyNumber *int16
	Earned                     *bool
	RbiBatterName              *string
	RbiBatterTeamName          *string
	RbiBatterJerseyNumber      *int16
	Description                string
}

func (q *Queries) ListRecordRunners(ctx context.Context, playIds []string) ([]ListRecordRunnersRow, error) {
	rows, err := q.db.Query(ctx, listRecordRunners, playIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecordRunnersRow{}
	for rows.Next() {
		var i ListRecordRunnersRow
		if err := rows.Scan(
			&i.RPlayID,
			&i.Sequence,
			&i.RunnerName,
			&i.RunnerTeamName,
			&i.RunnerJerseyNumber,
			&i.Result,
			&i.FromBase,
			&i.ToBase,
			&i.OutRecorded,
			&i.Scored,
			&i.ChargedPitcherName,
			&i.ChargedPitcherTeamName,
			&i.ChargedPitcherJerseyNumber,
			&i.Earned,
			&i.RbiBatterName,
			&i.RbiBatterTeamName,
			&i.RbiBatterJerseyNumber,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSelectedMatches = `-- name: ListSelectedMatches :many
SELECT m.id::text, m.scheduled_at, home.name AS home_team_name, away.name AS away_team_name, m.location, m.status
FROM matches m JOIN teams home ON home.id=m.home_team_id JOIN teams away ON away.id=m.away_team_id
WHERE m.deleted_at IS NULL AND home.deleted_at IS NULL AND away.deleted_at IS NULL
  AND (COALESCE(cardinality($1::text[]),0)=0 OR home.name=ANY($1::text[]) OR away.name=ANY($1::text[]))
  AND ($2::timestamptz IS NULL OR m.scheduled_at>=$2::timestamptz)
  AND ($3::timestamptz IS NULL OR m.scheduled_at<=$3::timestamptz)
ORDER BY m.scheduled_at DESC,m.id DESC LIMIT NULLIF($4::int,0)
`

type ListSelectedMatchesParams struct {
	ParticipantNames []string
	ScheduledFrom    pgtype.Timestamptz
	ScheduledTo      pgtype.Timestamptz
	RowLimit         int32
}

type ListSelectedMatchesRow struct {
	MID          string
	ScheduledAt  pgtype.Timestamptz
	HomeTeamName string
	AwayTeamName string
	Location     string
	Status       int16
}

func (q *Queries) ListSelectedMatches(ctx context.Context, arg ListSelectedMatchesParams) ([]ListSelectedMatchesRow, error) {
	rows, err := q.db.Query(ctx, listSelectedMatches,
		arg.ParticipantNames,
		arg.ScheduledFrom,
		arg.ScheduledTo,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSelectedMatchesRow{}
	for rows.Next() {
		var i ListSelectedMatchesRow
		if err := rows.Scan(
			&i.MID,
			&i.ScheduledAt,
			&i.HomeTeamName,
			&i.AwayTeamName,
			&i.Location,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
