// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Lineup struct {
	ID            string
	MatchID       string
	TeamID        string
	Kind          int16
	VariantNumber int16
	VariantName   string
	PlayerID      string
	BattingOrder  int16
	Position      int16
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type Match struct {
	ID          string
	HomeTeamID  string
	AwayTeamID  string
	ScheduledAt pgtype.Timestamptz
	Location    string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	Status      int16
}

type Play struct {
	ID                     string
	MatchID                string
	Sequence               int32
	Inning                 int16
	Half                   int16
	BattingOrder           int16
	BatterID               string
	StartingPitcherID      string
	BattingResult          int16
	ResultDescription      string
	BeforeOuts             int16
	BeforeHomeScore        int32
	BeforeAwayScore        int32
	BeforeRunnerOnFirstID  pgtype.UUID
	BeforeRunnerOnSecondID pgtype.UUID
	BeforeRunnerOnThirdID  pgtype.UUID
	AfterOuts              int16
	AfterHomeScore         int32
	AfterAwayScore         int32
	AfterRunnerOnFirstID   pgtype.UUID
	AfterRunnerOnSecondID  pgtype.UUID
	AfterRunnerOnThirdID   pgtype.UUID
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	DeletedAt              pgtype.Timestamptz
}

type PlayFieldingResult struct {
	ID          string
	PlayID      string
	Sequence    int16
	FielderID   string
	Position    int16
	Result      int16
	Description string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type PlayPitchingResult struct {
	ID            string
	PlayID        string
	Sequence      int16
	PitcherID     string
	BatterID      string
	Result        int16
	BallsBefore   int16
	StrikesBefore int16
	BallsAfter    int16
	StrikesAfter  int16
	PitchType     string
	Velocity      *float64
	Zone          *int16
	Description   string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type PlayRunnerResult struct {
	ID               string
	PlayID           string
	Sequence         int16
	RunnerID         string
	Result           int16
	FromBase         int16
	ToBase           *int16
	OutRecorded      bool
	Scored           bool
	ChargedPitcherID pgtype.UUID
	Earned           *bool
	RbiBatterID      pgtype.UUID
	Description      string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type Player struct {
	ID            string
	TeamID        string
	JerseyNumber  int16
	Name          string
	BattingFlags  int16
	ThrowingFlags int16
	PositionFlags int16
	Active        bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type Team struct {
	ID        string
	Name      string
	Active    bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type TrainingRecord struct {
	ID           string
	PlayerID     string
	TrainingDate pgtype.Date
	Content      string
	Reflection   string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}
