// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: play_write.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlay = `-- name: CreatePlay :exec
INSERT INTO plays (id, match_id, sequence, inning, half, batting_order, batter_id, starting_pitcher_id, batting_result, result_description, before_outs, before_home_score, before_away_score, before_runner_on_first_id, before_runner_on_second_id, before_runner_on_third_id, after_outs, after_home_score, after_away_score, after_runner_on_first_id, after_runner_on_second_id, after_runner_on_third_id, created_at, updated_at, deleted_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25)
`

type CreatePlayParams struct {
	ID                     string
	MatchID                string
	Sequence               int32
	Inning                 int16
	Half                   int16
	BattingOrder           int16
	BatterID               string
	StartingPitcherID      string
	BattingResult          int16
	ResultDescription      string
	BeforeOuts             int16
	BeforeHomeScore        int32
	BeforeAwayScore        int32
	BeforeRunnerOnFirstID  pgtype.UUID
	BeforeRunnerOnSecondID pgtype.UUID
	BeforeRunnerOnThirdID  pgtype.UUID
	AfterOuts              int16
	AfterHomeScore         int32
	AfterAwayScore         int32
	AfterRunnerOnFirstID   pgtype.UUID
	AfterRunnerOnSecondID  pgtype.UUID
	AfterRunnerOnThirdID   pgtype.UUID
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	DeletedAt              pgtype.Timestamptz
}

func (q *Queries) CreatePlay(ctx context.Context, arg CreatePlayParams) error {
	_, err := q.db.Exec(ctx, createPlay,
		arg.ID,
		arg.MatchID,
		arg.Sequence,
		arg.Inning,
		arg.Half,
		arg.BattingOrder,
		arg.BatterID,
		arg.StartingPitcherID,
		arg.BattingResult,
		arg.ResultDescription,
		arg.BeforeOuts,
		arg.BeforeHomeScore,
		arg.BeforeAwayScore,
		arg.BeforeRunnerOnFirstID,
		arg.BeforeRunnerOnSecondID,
		arg.BeforeRunnerOnThirdID,
		arg.AfterOuts,
		arg.AfterHomeScore,
		arg.AfterAwayScore,
		arg.AfterRunnerOnFirstID,
		arg.AfterRunnerOnSecondID,
		arg.AfterRunnerOnThirdID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const createPlayFieldingOutcome = `-- name: CreatePlayFieldingOutcome :exec
INSERT INTO play_fielding_results (id, play_id, sequence, fielder_id, position, result, description, created_at, updated_at, deleted_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
`

type CreatePlayFieldingOutcomeParams struct {
	ID          string
	PlayID      string
	Sequence    int16
	FielderID   string
	Position    int16
	Result      int16
	Description string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

func (q *Queries) CreatePlayFieldingOutcome(ctx context.Context, arg CreatePlayFieldingOutcomeParams) error {
	_, err := q.db.Exec(ctx, createPlayFieldingOutcome,
		arg.ID,
		arg.PlayID,
		arg.Sequence,
		arg.FielderID,
		arg.Position,
		arg.Result,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const createPlayPitch = `-- name: CreatePlayPitch :exec
INSERT INTO play_pitching_results (id, play_id, sequence, pitcher_id, batter_id, result, balls_before, strikes_before, balls_after, strikes_after, pitch_type, velocity, zone, description, created_at, updated_at, deleted_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)
`

type CreatePlayPitchParams struct {
	ID            string
	PlayID        string
	Sequence      int16
	PitcherID     string
	BatterID      string
	Result        int16
	BallsBefore   int16
	StrikesBefore int16
	BallsAfter    int16
	StrikesAfter  int16
	PitchType     string
	Velocity      *float64
	Zone          *int16
	Description   string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

func (q *Queries) CreatePlayPitch(ctx context.Context, arg CreatePlayPitchParams) error {
	_, err := q.db.Exec(ctx, createPlayPitch,
		arg.ID,
		arg.PlayID,
		arg.Sequence,
		arg.PitcherID,
		arg.BatterID,
		arg.Result,
		arg.BallsBefore,
		arg.StrikesBefore,
		arg.BallsAfter,
		arg.StrikesAfter,
		arg.PitchType,
		arg.Velocity,
		arg.Zone,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const createPlayRunnerOutcome = `-- name: CreatePlayRunnerOutcome :exec
INSERT INTO play_runner_results (id, play_id, sequence, runner_id, result, from_base, to_base, out_recorded, scored, charged_pitcher_id, earned, rbi_batter_id, description, created_at, updated_at, deleted_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)
`

type CreatePlayRunnerOutcomeParams struct {
	ID               string
	PlayID           string
	Sequence         int16
	RunnerID         string
	Result           int16
	FromBase         int16
	ToBase           *int16
	OutRecorded      bool
	Scored           bool
	ChargedPitcherID pgtype.UUID
	Earned           *bool
	RbiBatterID      pgtype.UUID
	Description      string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

func (q *Queries) CreatePlayRunnerOutcome(ctx context.Context, arg CreatePlayRunnerOutcomeParams) error {
	_, err := q.db.Exec(ctx, createPlayRunnerOutcome,
		arg.ID,
		arg.PlayID,
		arg.Sequence,
		arg.RunnerID,
		arg.Result,
		arg.FromBase,
		arg.ToBase,
		arg.OutRecorded,
		arg.Scored,
		arg.ChargedPitcherID,
		arg.Earned,
		arg.RbiBatterID,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const softDeletePlay = `-- name: SoftDeletePlay :execrows
UPDATE plays SET deleted_at=$1, updated_at=$1 WHERE id=$2 AND deleted_at IS NULL
`

type SoftDeletePlayParams struct {
	DeletedAt pgtype.Timestamptz
	ID        string
}

func (q *Queries) SoftDeletePlay(ctx context.Context, arg SoftDeletePlayParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeletePlay, arg.DeletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeletePlayFieldingOutcomes = `-- name: SoftDeletePlayFieldingOutcomes :exec
UPDATE play_fielding_results SET deleted_at=$1, updated_at=$1 WHERE play_id=$2 AND deleted_at IS NULL
`

type SoftDeletePlayFieldingOutcomesParams struct {
	DeletedAt pgtype.Timestamptz
	PlayID    string
}

func (q *Queries) SoftDeletePlayFieldingOutcomes(ctx context.Context, arg SoftDeletePlayFieldingOutcomesParams) error {
	_, err := q.db.Exec(ctx, softDeletePlayFieldingOutcomes, arg.DeletedAt, arg.PlayID)
	return err
}

const softDeletePlayPitches = `-- name: SoftDeletePlayPitches :exec
UPDATE play_pitching_results SET deleted_at=$1, updated_at=$1 WHERE play_id=$2 AND deleted_at IS NULL
`

type SoftDeletePlayPitchesParams struct {
	DeletedAt pgtype.Timestamptz
	PlayID    string
}

func (q *Queries) SoftDeletePlayPitches(ctx context.Context, arg SoftDeletePlayPitchesParams) error {
	_, err := q.db.Exec(ctx, softDeletePlayPitches, arg.DeletedAt, arg.PlayID)
	return err
}

const softDeletePlayRunnerOutcomes = `-- name: SoftDeletePlayRunnerOutcomes :exec
UPDATE play_runner_results SET deleted_at=$1, updated_at=$1 WHERE play_id=$2 AND deleted_at IS NULL
`

type SoftDeletePlayRunnerOutcomesParams struct {
	DeletedAt pgtype.Timestamptz
	PlayID    string
}

func (q *Queries) SoftDeletePlayRunnerOutcomes(ctx context.Context, arg SoftDeletePlayRunnerOutcomesParams) error {
	_, err := q.db.Exec(ctx, softDeletePlayRunnerOutcomes, arg.DeletedAt, arg.PlayID)
	return err
}

const softDeletePlaysByMatch = `-- name: SoftDeletePlaysByMatch :exec
UPDATE plays SET deleted_at=$1, updated_at=$1 WHERE match_id=$2 AND deleted_at IS NULL
`

type SoftDeletePlaysByMatchParams struct {
	DeletedAt pgtype.Timestamptz
	MatchID   string
}

func (q *Queries) SoftDeletePlaysByMatch(ctx context.Context, arg SoftDeletePlaysByMatchParams) error {
	_, err := q.db.Exec(ctx, softDeletePlaysByMatch, arg.DeletedAt, arg.MatchID)
	return err
}

const updatePlay = `-- name: UpdatePlay :execrows
UPDATE plays SET match_id=$1, sequence=$2, inning=$3, half=$4, batting_order=$5, batter_id=$6, starting_pitcher_id=$7, batting_result=$8, result_description=$9,
 before_outs=$10, before_home_score=$11, before_away_score=$12, before_runner_on_first_id=$13, before_runner_on_second_id=$14, before_runner_on_third_id=$15,
 after_outs=$16, after_home_score=$17, after_away_score=$18, after_runner_on_first_id=$19, after_runner_on_second_id=$20, after_runner_on_third_id=$21,
 created_at=$22, updated_at=$23, deleted_at=$24
WHERE id=$25 AND deleted_at IS NULL
`

type UpdatePlayParams struct {
	MatchID                string
	Sequence               int32
	Inning                 int16
	Half                   int16
	BattingOrder           int16
	BatterID               string
	StartingPitcherID      string
	BattingResult          int16
	ResultDescription      string
	BeforeOuts             int16
	BeforeHomeScore        int32
	BeforeAwayScore        int32
	BeforeRunnerOnFirstID  pgtype.UUID
	BeforeRunnerOnSecondID pgtype.UUID
	BeforeRunnerOnThirdID  pgtype.UUID
	AfterOuts              int16
	AfterHomeScore         int32
	AfterAwayScore         int32
	AfterRunnerOnFirstID   pgtype.UUID
	AfterRunnerOnSecondID  pgtype.UUID
	AfterRunnerOnThirdID   pgtype.UUID
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	DeletedAt              pgtype.Timestamptz
	ID                     string
}

func (q *Queries) UpdatePlay(ctx context.Context, arg UpdatePlayParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePlay,
		arg.MatchID,
		arg.Sequence,
		arg.Inning,
		arg.Half,
		arg.BattingOrder,
		arg.BatterID,
		arg.StartingPitcherID,
		arg.BattingResult,
		arg.ResultDescription,
		arg.BeforeOuts,
		arg.BeforeHomeScore,
		arg.BeforeAwayScore,
		arg.BeforeRunnerOnFirstID,
		arg.BeforeRunnerOnSecondID,
		arg.BeforeRunnerOnThirdID,
		arg.AfterOuts,
		arg.AfterHomeScore,
		arg.AfterAwayScore,
		arg.AfterRunnerOnFirstID,
		arg.AfterRunnerOnSecondID,
		arg.AfterRunnerOnThirdID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
