// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: play_read.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlay = `-- name: GetPlay :one
SELECT id::text, match_id::text, sequence, inning, half, batting_order, batter_id::text, starting_pitcher_id::text, batting_result, result_description,
       before_outs, before_home_score, before_away_score, COALESCE(before_runner_on_first_id::text, ''::text) AS before_runner_on_first_id, COALESCE(before_runner_on_second_id::text, ''::text) AS before_runner_on_second_id, COALESCE(before_runner_on_third_id::text, ''::text) AS before_runner_on_third_id,
       after_outs, after_home_score, after_away_score, COALESCE(after_runner_on_first_id::text, ''::text) AS after_runner_on_first_id, COALESCE(after_runner_on_second_id::text, ''::text) AS after_runner_on_second_id, COALESCE(after_runner_on_third_id::text, ''::text) AS after_runner_on_third_id,
       created_at, updated_at, deleted_at
FROM plays WHERE id=$1 AND deleted_at IS NULL
`

type GetPlayRow struct {
	ID                     string
	MatchID                string
	Sequence               int32
	Inning                 int16
	Half                   int16
	BattingOrder           int16
	BatterID               string
	StartingPitcherID      string
	BattingResult          int16
	ResultDescription      string
	BeforeOuts             int16
	BeforeHomeScore        int32
	BeforeAwayScore        int32
	BeforeRunnerOnFirstID  interface{}
	BeforeRunnerOnSecondID interface{}
	BeforeRunnerOnThirdID  interface{}
	AfterOuts              int16
	AfterHomeScore         int32
	AfterAwayScore         int32
	AfterRunnerOnFirstID   interface{}
	AfterRunnerOnSecondID  interface{}
	AfterRunnerOnThirdID   interface{}
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	DeletedAt              pgtype.Timestamptz
}

func (q *Queries) GetPlay(ctx context.Context, id string) (GetPlayRow, error) {
	row := q.db.QueryRow(ctx, getPlay, id)
	var i GetPlayRow
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.Sequence,
		&i.Inning,
		&i.Half,
		&i.BattingOrder,
		&i.BatterID,
		&i.StartingPitcherID,
		&i.BattingResult,
		&i.ResultDescription,
		&i.BeforeOuts,
		&i.BeforeHomeScore,
		&i.BeforeAwayScore,
		&i.BeforeRunnerOnFirstID,
		&i.BeforeRunnerOnSecondID,
		&i.BeforeRunnerOnThirdID,
		&i.AfterOuts,
		&i.AfterHomeScore,
		&i.AfterAwayScore,
		&i.AfterRunnerOnFirstID,
		&i.AfterRunnerOnSecondID,
		&i.AfterRunnerOnThirdID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPlayFieldingOutcomes = `-- name: ListPlayFieldingOutcomes :many
SELECT id::text, sequence, fielder_id::text, position, result, description, created_at, updated_at, deleted_at
FROM play_fielding_results WHERE play_id=$1 AND deleted_at IS NULL ORDER BY sequence
`

type ListPlayFieldingOutcomesRow struct {
	ID          string
	Sequence    int16
	FielderID   string
	Position    int16
	Result      int16
	Description string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

func (q *Queries) ListPlayFieldingOutcomes(ctx context.Context, playID string) ([]ListPlayFieldingOutcomesRow, error) {
	rows, err := q.db.Query(ctx, listPlayFieldingOutcomes, playID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayFieldingOutcomesRow{}
	for rows.Next() {
		var i ListPlayFieldingOutcomesRow
		if err := rows.Scan(
			&i.ID,
			&i.Sequence,
			&i.FielderID,
			&i.Position,
			&i.Result,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayIDsByMatch = `-- name: ListPlayIDsByMatch :many
SELECT id::text FROM plays WHERE match_id=$1 AND deleted_at IS NULL ORDER BY sequence
`

func (q *Queries) ListPlayIDsByMatch(ctx context.Context, matchID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listPlayIDsByMatch, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayPitches = `-- name: ListPlayPitches :many
SELECT id::text, sequence, pitcher_id::text, batter_id::text, result, balls_before, strikes_before, balls_after, strikes_after, pitch_type, velocity, zone, description, created_at, updated_at, deleted_at
FROM play_pitching_results WHERE play_id=$1 AND deleted_at IS NULL ORDER BY sequence
`

type ListPlayPitchesRow struct {
	ID            string
	Sequence      int16
	PitcherID     string
	BatterID      string
	Result        int16
	BallsBefore   int16
	StrikesBefore int16
	BallsAfter    int16
	StrikesAfter  int16
	PitchType     string
	Velocity      *float64
	Zone          *int16
	Description   string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

func (q *Queries) ListPlayPitches(ctx context.Context, playID string) ([]ListPlayPitchesRow, error) {
	rows, err := q.db.Query(ctx, listPlayPitches, playID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayPitchesRow{}
	for rows.Next() {
		var i ListPlayPitchesRow
		if err := rows.Scan(
			&i.ID,
			&i.Sequence,
			&i.PitcherID,
			&i.BatterID,
			&i.Result,
			&i.BallsBefore,
			&i.StrikesBefore,
			&i.BallsAfter,
			&i.StrikesAfter,
			&i.PitchType,
			&i.Velocity,
			&i.Zone,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayRunnerOutcomes = `-- name: ListPlayRunnerOutcomes :many
SELECT id::text, sequence, runner_id::text, result, from_base, to_base, out_recorded, scored, COALESCE(charged_pitcher_id::text, ''::text) AS charged_pitcher_id, earned, COALESCE(rbi_batter_id::text, ''::text) AS rbi_batter_id, description, created_at, updated_at, deleted_at
FROM play_runner_results WHERE play_id=$1 AND deleted_at IS NULL ORDER BY sequence
`

type ListPlayRunnerOutcomesRow struct {
	ID               string
	Sequence         int16
	RunnerID         string
	Result           int16
	FromBase         int16
	ToBase           *int16
	OutRecorded      bool
	Scored           bool
	ChargedPitcherID interface{}
	Earned           *bool
	RbiBatterID      interface{}
	Description      string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

func (q *Queries) ListPlayRunnerOutcomes(ctx context.Context, playID string) ([]ListPlayRunnerOutcomesRow, error) {
	rows, err := q.db.Query(ctx, listPlayRunnerOutcomes, playID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayRunnerOutcomesRow{}
	for rows.Next() {
		var i ListPlayRunnerOutcomesRow
		if err := rows.Scan(
			&i.ID,
			&i.Sequence,
			&i.RunnerID,
			&i.Result,
			&i.FromBase,
			&i.ToBase,
			&i.OutRecorded,
			&i.Scored,
			&i.ChargedPitcherID,
			&i.Earned,
			&i.RbiBatterID,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
