// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const auditDuplicateJerseys = `-- name: AuditDuplicateJerseys :many
SELECT team_id::text AS team_id, ''::text AS player_id, jersey_number, count(*)::int AS issue_count
FROM players WHERE deleted_at IS NULL GROUP BY team_id,jersey_number HAVING count(*)>1
`

type AuditDuplicateJerseysRow struct {
	TeamID       string
	PlayerID     string
	JerseyNumber int16
	IssueCount   int32
}

func (q *Queries) AuditDuplicateJerseys(ctx context.Context) ([]AuditDuplicateJerseysRow, error) {
	rows, err := q.db.Query(ctx, auditDuplicateJerseys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditDuplicateJerseysRow{}
	for rows.Next() {
		var i AuditDuplicateJerseysRow
		if err := rows.Scan(
			&i.TeamID,
			&i.PlayerID,
			&i.JerseyNumber,
			&i.IssueCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const auditOrphanTeams = `-- name: AuditOrphanTeams :many
SELECT p.team_id::text AS team_id, p.id::text AS player_id, p.jersey_number, 1::int AS issue_count
FROM players p LEFT JOIN teams t ON t.id=p.team_id AND t.deleted_at IS NULL
WHERE p.deleted_at IS NULL AND t.id IS NULL
`

type AuditOrphanTeamsRow struct {
	TeamID       string
	PlayerID     string
	JerseyNumber int16
	IssueCount   int32
}

func (q *Queries) AuditOrphanTeams(ctx context.Context) ([]AuditOrphanTeamsRow, error) {
	rows, err := q.db.Query(ctx, auditOrphanTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditOrphanTeamsRow{}
	for rows.Next() {
		var i AuditOrphanTeamsRow
		if err := rows.Scan(
			&i.TeamID,
			&i.PlayerID,
			&i.JerseyNumber,
			&i.IssueCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createPlayer = `-- name: CreatePlayer :exec
INSERT INTO players (id, team_id, jersey_number, name, batting_flags, throwing_flags, position_flags, active, created_at, updated_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreatePlayerParams struct {
	ID            string
	TeamID        string
	JerseyNumber  int16
	Name          string
	BattingFlags  int16
	ThrowingFlags int16
	PositionFlags int16
	Active        bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) error {
	_, err := q.db.Exec(ctx, createPlayer,
		arg.ID,
		arg.TeamID,
		arg.JerseyNumber,
		arg.Name,
		arg.BattingFlags,
		arg.ThrowingFlags,
		arg.PositionFlags,
		arg.Active,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const getPlayer = `-- name: GetPlayer :one
SELECT id::text, team_id::text, jersey_number, name, batting_flags, throwing_flags, position_flags, active, created_at, updated_at, deleted_at
FROM players
WHERE id = $1 AND deleted_at IS NULL
`

type GetPlayerRow struct {
	ID            string
	TeamID        string
	JerseyNumber  int16
	Name          string
	BattingFlags  int16
	ThrowingFlags int16
	PositionFlags int16
	Active        bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

func (q *Queries) GetPlayer(ctx context.Context, id string) (GetPlayerRow, error) {
	row := q.db.QueryRow(ctx, getPlayer, id)
	var i GetPlayerRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.JerseyNumber,
		&i.Name,
		&i.BattingFlags,
		&i.ThrowingFlags,
		&i.PositionFlags,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPlayersByTeamAndJerseys = `-- name: GetPlayersByTeamAndJerseys :many
WITH requested AS (
    SELECT
        split_part(value, '/', 1)::uuid AS team_id,
        split_part(value, '/', 2)::smallint AS jersey_number
    FROM unnest($1::text[]) AS requested(value)
)
SELECT p.id::text AS id, p.team_id::text AS team_id, p.jersey_number, p.name, p.batting_flags, p.throwing_flags, p.position_flags, p.active, p.created_at, p.updated_at, p.deleted_at
FROM requested r
JOIN players p ON p.team_id = r.team_id AND p.jersey_number = r.jersey_number
WHERE p.deleted_at IS NULL
ORDER BY p.team_id, p.jersey_number
`

type GetPlayersByTeamAndJerseysRow struct {
	ID            string
	TeamID        string
	JerseyNumber  int16
	Name          string
	BattingFlags  int16
	ThrowingFlags int16
	PositionFlags int16
	Active        bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

func (q *Queries) GetPlayersByTeamAndJerseys(ctx context.Context, keys []string) ([]GetPlayersByTeamAndJerseysRow, error) {
	rows, err := q.db.Query(ctx, getPlayersByTeamAndJerseys, keys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayersByTeamAndJerseysRow{}
	for rows.Next() {
		var i GetPlayersByTeamAndJerseysRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.JerseyNumber,
			&i.Name,
			&i.BattingFlags,
			&i.ThrowingFlags,
			&i.PositionFlags,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerViews = `-- name: ListPlayerViews :many
SELECT p.name, t.name AS team_name, p.jersey_number, p.position_flags, p.active
FROM players p JOIN teams t ON t.id=p.team_id
WHERE p.deleted_at IS NULL AND t.deleted_at IS NULL
  AND ($1::text='' OR t.name=$1::text)
  AND ($2::smallint=0 OR (p.position_flags & $2::smallint)<>0)
  AND ($3::smallint IS NULL OR p.jersey_number=$3::smallint)
ORDER BY p.jersey_number,p.name,p.id
`

type ListPlayerViewsParams struct {
	TeamName     string
	PositionAny  int16
	JerseyNumber *int16
}

type ListPlayerViewsRow struct {
	Name          string
	TeamName      string
	JerseyNumber  int16
	PositionFlags int16
	Active        bool
}

func (q *Queries) ListPlayerViews(ctx context.Context, arg ListPlayerViewsParams) ([]ListPlayerViewsRow, error) {
	rows, err := q.db.Query(ctx, listPlayerViews, arg.TeamName, arg.PositionAny, arg.JerseyNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerViewsRow{}
	for rows.Next() {
		var i ListPlayerViewsRow
		if err := rows.Scan(
			&i.Name,
			&i.TeamName,
			&i.JerseyNumber,
			&i.PositionFlags,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayers = `-- name: ListPlayers :many
SELECT p.name, t.name, p.jersey_number, p.position_flags, p.active
FROM players p
JOIN teams t ON t.id = p.team_id AND t.deleted_at IS NULL
WHERE p.deleted_at IS NULL
  AND ($1::text IS NULL OR t.name = $1::text)
  AND ($2::text IS NULL OR p.name = $2::text)
ORDER BY t.name, p.jersey_number, p.name, p.id
`

type ListPlayersParams struct {
	TeamName   *string
	PlayerName *string
}

type ListPlayersRow struct {
	Name          string
	Name_2        string
	JerseyNumber  int16
	PositionFlags int16
	Active        bool
}

func (q *Queries) ListPlayers(ctx context.Context, arg ListPlayersParams) ([]ListPlayersRow, error) {
	rows, err := q.db.Query(ctx, listPlayers, arg.TeamName, arg.PlayerName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayersRow{}
	for rows.Next() {
		var i ListPlayersRow
		if err := rows.Scan(
			&i.Name,
			&i.Name_2,
			&i.JerseyNumber,
			&i.PositionFlags,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const playerJerseyOccupied = `-- name: PlayerJerseyOccupied :one
SELECT EXISTS(
    SELECT 1
    FROM players
WHERE team_id = $1
      AND jersey_number = $2
      AND deleted_at IS NULL
      AND ($3::uuid IS NULL OR id <> $3::uuid)
)
`

type PlayerJerseyOccupiedParams struct {
	TeamID         string
	JerseyNumber   int16
	ExceptPlayerID pgtype.UUID
}

func (q *Queries) PlayerJerseyOccupied(ctx context.Context, arg PlayerJerseyOccupiedParams) (bool, error) {
	row := q.db.QueryRow(ctx, playerJerseyOccupied, arg.TeamID, arg.JerseyNumber, arg.ExceptPlayerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeletePlayersByTeam = `-- name: SoftDeletePlayersByTeam :exec
UPDATE players
SET deleted_at = $1,
    updated_at = $1
WHERE team_id = $2 AND deleted_at IS NULL
`

type SoftDeletePlayersByTeamParams struct {
	DeletedAt pgtype.Timestamptz
	TeamID    string
}

func (q *Queries) SoftDeletePlayersByTeam(ctx context.Context, arg SoftDeletePlayersByTeamParams) error {
	_, err := q.db.Exec(ctx, softDeletePlayersByTeam, arg.DeletedAt, arg.TeamID)
	return err
}

const updatePlayer = `-- name: UpdatePlayer :execrows
UPDATE players
SET jersey_number = $1,
    name = $2,
    batting_flags = $3,
    throwing_flags = $4,
    position_flags = $5,
    active = $6,
    updated_at = $7,
    deleted_at = $8
WHERE id = $9 AND deleted_at IS NULL
`

type UpdatePlayerParams struct {
	JerseyNumber  int16
	Name          string
	BattingFlags  int16
	ThrowingFlags int16
	PositionFlags int16
	Active        bool
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	ID            string
}

func (q *Queries) UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePlayer,
		arg.JerseyNumber,
		arg.Name,
		arg.BattingFlags,
		arg.ThrowingFlags,
		arg.PositionFlags,
		arg.Active,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
