// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	AuditDuplicateJerseys(ctx context.Context) ([]AuditDuplicateJerseysRow, error)
	AuditOrphanTeams(ctx context.Context) ([]AuditOrphanTeamsRow, error)
	CreateLineupEntry(ctx context.Context, arg CreateLineupEntryParams) error
	CreateMatch(ctx context.Context, arg CreateMatchParams) error
	CreatePlay(ctx context.Context, arg CreatePlayParams) error
	CreatePlayFieldingOutcome(ctx context.Context, arg CreatePlayFieldingOutcomeParams) error
	CreatePlayPitch(ctx context.Context, arg CreatePlayPitchParams) error
	CreatePlayRunnerOutcome(ctx context.Context, arg CreatePlayRunnerOutcomeParams) error
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) error
	CreateTeam(ctx context.Context, arg CreateTeamParams) error
	CreateTrainingRecord(ctx context.Context, arg CreateTrainingRecordParams) error
	GetLineupEntries(ctx context.Context, arg GetLineupEntriesParams) ([]GetLineupEntriesRow, error)
	GetMatch(ctx context.Context, id string) (GetMatchRow, error)
	GetPlay(ctx context.Context, id string) (GetPlayRow, error)
	GetPlayer(ctx context.Context, id string) (GetPlayerRow, error)
	GetPlayersByTeamAndJerseys(ctx context.Context, keys []string) ([]GetPlayersByTeamAndJerseysRow, error)
	GetTeam(ctx context.Context, id string) (GetTeamRow, error)
	GetTeamsByNames(ctx context.Context, names []string) ([]GetTeamsByNamesRow, error)
	GetTrainingRecord(ctx context.Context, id string) (GetTrainingRecordRow, error)
	LineupNameOccupied(ctx context.Context, arg LineupNameOccupiedParams) (bool, error)
	ListFieldingLines(ctx context.Context, matchIds []string) ([]ListFieldingLinesRow, error)
	ListLineupKeysByMatch(ctx context.Context, matchID string) ([]ListLineupKeysByMatchRow, error)
	ListMatchFinalScores(ctx context.Context, matchIds []string) ([]ListMatchFinalScoresRow, error)
	ListMatchLineupRows(ctx context.Context, matchIds []string) ([]ListMatchLineupRowsRow, error)
	ListMatchRecordEvents(ctx context.Context, matchIds []string) ([]ListMatchRecordEventsRow, error)
	ListOffenseLines(ctx context.Context, matchIds []string) ([]ListOffenseLinesRow, error)
	ListPitchingLines(ctx context.Context, matchIds []string) ([]ListPitchingLinesRow, error)
	ListPlayFieldingOutcomes(ctx context.Context, playID string) ([]ListPlayFieldingOutcomesRow, error)
	ListPlayIDsByMatch(ctx context.Context, matchID string) ([]string, error)
	ListPlayPitches(ctx context.Context, playID string) ([]ListPlayPitchesRow, error)
	ListPlayRunnerOutcomes(ctx context.Context, playID string) ([]ListPlayRunnerOutcomesRow, error)
	ListPlayerViews(ctx context.Context, arg ListPlayerViewsParams) ([]ListPlayerViewsRow, error)
	ListPlayers(ctx context.Context, arg ListPlayersParams) ([]ListPlayersRow, error)
	ListRecordFielding(ctx context.Context, playIds []string) ([]ListRecordFieldingRow, error)
	ListRecordPitches(ctx context.Context, playIds []string) ([]ListRecordPitchesRow, error)
	ListRecordRunners(ctx context.Context, playIds []string) ([]ListRecordRunnersRow, error)
	ListSelectedMatches(ctx context.Context, arg ListSelectedMatchesParams) ([]ListSelectedMatchesRow, error)
	ListStoredMatches(ctx context.Context) ([]ListStoredMatchesRow, error)
	ListTeams(ctx context.Context, activeOnly bool) ([]ListTeamsRow, error)
	ListTrainingRecords(ctx context.Context, arg ListTrainingRecordsParams) ([]ListTrainingRecordsRow, error)
	PlayerJerseyOccupied(ctx context.Context, arg PlayerJerseyOccupiedParams) (bool, error)
	SoftDeleteLineup(ctx context.Context, arg SoftDeleteLineupParams) (int64, error)
	SoftDeleteLineupsByMatch(ctx context.Context, arg SoftDeleteLineupsByMatchParams) error
	SoftDeletePlay(ctx context.Context, arg SoftDeletePlayParams) (int64, error)
	SoftDeletePlayFieldingOutcomes(ctx context.Context, arg SoftDeletePlayFieldingOutcomesParams) error
	SoftDeletePlayPitches(ctx context.Context, arg SoftDeletePlayPitchesParams) error
	SoftDeletePlayRunnerOutcomes(ctx context.Context, arg SoftDeletePlayRunnerOutcomesParams) error
	SoftDeletePlayersByTeam(ctx context.Context, arg SoftDeletePlayersByTeamParams) error
	SoftDeletePlaysByMatch(ctx context.Context, arg SoftDeletePlaysByMatchParams) error
	SoftDeleteTrainingRecordsByPlayer(ctx context.Context, arg SoftDeleteTrainingRecordsByPlayerParams) error
	UpdateMatch(ctx context.Context, arg UpdateMatchParams) (int64, error)
	UpdatePlay(ctx context.Context, arg UpdatePlayParams) (int64, error)
	UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (int64, error)
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (int64, error)
	UpdateTrainingRecord(ctx context.Context, arg UpdateTrainingRecordParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
