// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTeam = `-- name: CreateTeam :exec
INSERT INTO teams (id, name, active, created_at, updated_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateTeamParams struct {
	ID        string
	Name      string
	Active    bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) error {
	_, err := q.db.Exec(ctx, createTeam,
		arg.ID,
		arg.Name,
		arg.Active,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const getTeam = `-- name: GetTeam :one
SELECT id::text, name, active, created_at, updated_at, deleted_at
FROM teams
WHERE id = $1 AND deleted_at IS NULL
`

type GetTeamRow struct {
	ID        string
	Name      string
	Active    bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) GetTeam(ctx context.Context, id string) (GetTeamRow, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i GetTeamRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTeams = `-- name: ListTeams :many
SELECT id::text, name, active, created_at, updated_at, deleted_at
FROM teams
WHERE deleted_at IS NULL
  AND (NOT $1::boolean OR active)
ORDER BY name, id
`

type ListTeamsRow struct {
	ID        string
	Name      string
	Active    bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) ListTeams(ctx context.Context, activeOnly bool) ([]ListTeamsRow, error) {
	rows, err := q.db.Query(ctx, listTeams, activeOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsRow{}
	for rows.Next() {
		var i ListTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeam = `-- name: UpdateTeam :execrows
UPDATE teams
SET name = $1,
    active = $2,
    updated_at = $3,
    deleted_at = $4
WHERE id = $5 AND deleted_at IS NULL
`

type UpdateTeamParams struct {
	Name      string
	Active    bool
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	ID        string
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTeam,
		arg.Name,
		arg.Active,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
