// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: training.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrainingRecord = `-- name: CreateTrainingRecord :exec
INSERT INTO training_records (id, player_id, training_date, content, reflection, created_at, updated_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateTrainingRecordParams struct {
	ID           string
	PlayerID     string
	TrainingDate pgtype.Date
	Content      string
	Reflection   string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

func (q *Queries) CreateTrainingRecord(ctx context.Context, arg CreateTrainingRecordParams) error {
	_, err := q.db.Exec(ctx, createTrainingRecord,
		arg.ID,
		arg.PlayerID,
		arg.TrainingDate,
		arg.Content,
		arg.Reflection,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const getTrainingRecord = `-- name: GetTrainingRecord :one
SELECT id::text, player_id::text, training_date, content, reflection, created_at, updated_at, deleted_at
FROM training_records
WHERE id = $1 AND deleted_at IS NULL
`

type GetTrainingRecordRow struct {
	ID           string
	PlayerID     string
	TrainingDate pgtype.Date
	Content      string
	Reflection   string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

func (q *Queries) GetTrainingRecord(ctx context.Context, id string) (GetTrainingRecordRow, error) {
	row := q.db.QueryRow(ctx, getTrainingRecord, id)
	var i GetTrainingRecordRow
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.TrainingDate,
		&i.Content,
		&i.Reflection,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTrainingRecords = `-- name: ListTrainingRecords :many
SELECT id::text, player_id::text, training_date, content, reflection, created_at, updated_at, deleted_at
FROM training_records
WHERE player_id = $1
  AND deleted_at IS NULL
  AND ($2::date IS NULL OR training_date >= $2)
  AND ($3::date IS NULL OR training_date <= $3)
ORDER BY training_date DESC, id
`

type ListTrainingRecordsParams struct {
	PlayerID string
	Column2  pgtype.Date
	Column3  pgtype.Date
}

type ListTrainingRecordsRow struct {
	ID           string
	PlayerID     string
	TrainingDate pgtype.Date
	Content      string
	Reflection   string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

func (q *Queries) ListTrainingRecords(ctx context.Context, arg ListTrainingRecordsParams) ([]ListTrainingRecordsRow, error) {
	rows, err := q.db.Query(ctx, listTrainingRecords, arg.PlayerID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrainingRecordsRow{}
	for rows.Next() {
		var i ListTrainingRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.TrainingDate,
			&i.Content,
			&i.Reflection,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrainingRecordsByPlayers = `-- name: ListTrainingRecordsByPlayers :many
SELECT id::text, player_id::text, training_date, content, reflection, created_at, updated_at, deleted_at
FROM training_records
WHERE deleted_at IS NULL
  AND (COALESCE(cardinality($1::uuid[]),0)=0 OR player_id = ANY($1::uuid[]))
  AND ($2::date IS NULL OR training_date >= $2::date)
  AND ($3::date IS NULL OR training_date <= $3::date)
ORDER BY training_date DESC, player_id, id
LIMIT $4
`

type ListTrainingRecordsByPlayersParams struct {
	PlayerIds []string
	DateFrom  pgtype.Date
	DateTo    pgtype.Date
	LimitRows int32
}

type ListTrainingRecordsByPlayersRow struct {
	ID           string
	PlayerID     string
	TrainingDate pgtype.Date
	Content      string
	Reflection   string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

func (q *Queries) ListTrainingRecordsByPlayers(ctx context.Context, arg ListTrainingRecordsByPlayersParams) ([]ListTrainingRecordsByPlayersRow, error) {
	rows, err := q.db.Query(ctx, listTrainingRecordsByPlayers,
		arg.PlayerIds,
		arg.DateFrom,
		arg.DateTo,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrainingRecordsByPlayersRow{}
	for rows.Next() {
		var i ListTrainingRecordsByPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.TrainingDate,
			&i.Content,
			&i.Reflection,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTrainingRecordsByPlayer = `-- name: SoftDeleteTrainingRecordsByPlayer :exec
UPDATE training_records
SET deleted_at = $1,
    updated_at = $1
WHERE player_id = $2 AND deleted_at IS NULL
`

type SoftDeleteTrainingRecordsByPlayerParams struct {
	DeletedAt pgtype.Timestamptz
	PlayerID  string
}

func (q *Queries) SoftDeleteTrainingRecordsByPlayer(ctx context.Context, arg SoftDeleteTrainingRecordsByPlayerParams) error {
	_, err := q.db.Exec(ctx, softDeleteTrainingRecordsByPlayer, arg.DeletedAt, arg.PlayerID)
	return err
}

const updateTrainingRecord = `-- name: UpdateTrainingRecord :execrows
UPDATE training_records
SET content = $1,
    reflection = $2,
    updated_at = $3,
    deleted_at = $4
WHERE id = $5 AND deleted_at IS NULL
`

type UpdateTrainingRecordParams struct {
	Content    string
	Reflection string
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	ID         string
}

func (q *Queries) UpdateTrainingRecord(ctx context.Context, arg UpdateTrainingRecordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTrainingRecord,
		arg.Content,
		arg.Reflection,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
